openapi: 3.0.1
info:
  version: 1.2.0
  title: TopTeamsAPIv3
paths:
  /sentence/generate:
    post:
      summary: returns sentences
      parameters:
        - name: count
          in: query
          description: the number of sentences to be generated
          required: false
          schema:
            type: integer
            default: 1
        - name: tenses
          in: query
          description: tenses to be used
          required: false
          schema:
            type: array
            items:
              type: string
              enum: [ PAST, PRESENT, FUTURE ]
              example: PRESENT
            default: true
      responses:
        '200':
          description: Sentence

servers:
  - url: 'localhost:8080'